import { describe, expect, it } from "vitest"
import { applySessionEvent, emptyObserveState, hasActiveTool, hasBusyChild, observedHost } from "../../src/host/observe.js"

describe("host observe reducer", () => {
  it("ignores malformed events", () => {
    expect(applySessionEvent(emptyObserveState, null)).toBe(emptyObserveState)
    expect(applySessionEvent(emptyObserveState, "x")).toBe(emptyObserveState)
    expect(applySessionEvent(emptyObserveState, { type: "session.status" })).toBe(emptyObserveState)
  })
  it("maps session.status and ignores session.idle", () => {
    let state = applySessionEvent(emptyObserveState, { type: "session.status", data: { sessionID: "s", status: { type: "idle" } } })
    expect(observedHost(state, "s")).toBe("idle")
    state = applySessionEvent(state, { type: "session.idle", data: { sessionID: "s" } })
    expect(observedHost(state, "s")).toBe("idle")
    state = applySessionEvent(state, { type: "session.status", data: { sessionID: "s", status: { type: "busy" } } })
    expect(observedHost(state, "s")).toBe("busy")
    state = applySessionEvent(state, { type: "session.status", data: { sessionID: "s", status: { type: "retry" } } })
    expect(observedHost(state, "s")).toBe("retrying")
    state = applySessionEvent(state, { type: "session.status", data: { sessionID: "s", status: { type: "other" } } })
    expect(observedHost(state, "s")).toBe("unknown")
    expect(observedHost(emptyObserveState, "missing")).toBe("unknown")
  })
  it("tracks tools until success or failure", () => {
    let state = applySessionEvent(emptyObserveState, { type: "session.tool.input.started", data: { sessionID: "s", id: "t1" } })
    expect(hasActiveTool(state, "s")).toBe(true)
    state = applySessionEvent(state, { type: "session.tool.input.started", data: { sessionID: "s", id: "t1" } })
    expect(state.tools.s).toEqual(["t1"])
    state = applySessionEvent(state, { type: "session.tool.called", data: { sessionID: "s", id: "t2" } })
    expect(state.tools.s).toEqual(["t1", "t2"])
    state = applySessionEvent(state, { type: "session.tool.success", data: { sessionID: "s", id: "missing" } })
    expect(state.tools.s).toEqual(["t1", "t2"])
    state = applySessionEvent(state, { type: "session.tool.success", data: { sessionID: "s", id: "t1" } })
    expect(hasActiveTool(state, "s")).toBe(true)
    state = applySessionEvent(state, { type: "session.tool.failed", data: { sessionID: "s", id: "t2" } })
    expect(hasActiveTool(state, "s")).toBe(false)
    expect(state.tools.s).toBeUndefined()
    state = applySessionEvent(state, { type: "session.tool.called", data: { sessionID: "s", id: "keep" } })
    const other = applySessionEvent(state, { type: "session.tool.called", data: { sessionID: "s2", id: "x" } })
    const cleared = applySessionEvent(other, { type: "session.tool.success", data: { sessionID: "s2", id: "x" } })
    expect(cleared.tools.s2).toBeUndefined()
    expect(cleared.tools.s).toEqual(["keep"])
    expect(applySessionEvent(emptyObserveState, { type: "session.tool.input.started", data: { sessionID: "s" } })).toBe(emptyObserveState)
    expect(applySessionEvent(emptyObserveState, { type: "session.tool.success", data: { sessionID: "s", id: "t1" } })).toBe(emptyObserveState)
    expect(applySessionEvent(emptyObserveState, { type: "session.tool.failed", data: { sessionID: "s" } })).toBe(emptyObserveState)
    const withTool = applySessionEvent(emptyObserveState, { type: "session.tool.called", data: { sessionID: "s", id: "t1" } })
    expect(applySessionEvent(withTool, { type: "session.tool.failed", data: { sessionID: "s" } })).toBe(withTool)
  })
  it("treats non-idle children as busy", () => {
    let state = applySessionEvent(emptyObserveState, { type: "session.created", data: { sessionID: "c", parentID: "p" } })
    expect(hasBusyChild(state, "p")).toBe(true)
    state = applySessionEvent(state, { type: "session.status", data: { sessionID: "c", status: { type: "idle" } } })
    expect(hasBusyChild(state, "p")).toBe(false)
    state = applySessionEvent(state, { type: "session.forked", data: { sessionID: "f", parentID: "p" } })
    expect(hasBusyChild(state, "p")).toBe(true)
    state = applySessionEvent(state, { type: "session.deleted", data: { sessionID: "f" } })
    expect(hasBusyChild(state, "p")).toBe(false)
    expect(applySessionEvent(emptyObserveState, { type: "session.created", data: { sessionID: "c" } })).toBe(emptyObserveState)
    expect(hasActiveTool(emptyObserveState, "p")).toBe(false)
    const other = applySessionEvent(emptyObserveState, { type: "session.created", data: { sessionID: "c2", parentID: "p2" } })
    expect(hasBusyChild(other, "p")).toBe(false)
    expect(hasBusyChild(other, "p2")).toBe(true)
    const status = applySessionEvent(emptyObserveState, { type: "session.status", data: { sessionID: "c", status: { type: "idle" }, parentID: "p" } })
    expect(hasBusyChild(status, "p")).toBe(false)
    const idle = applySessionEvent(emptyObserveState, { type: "session.idle", data: { sessionID: "c", parentID: "p" } })
    expect(idle).toBe(emptyObserveState)
    expect(hasBusyChild(idle, "p")).toBe(false)
  })
})
